# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17bBgJ1EnVRS4njZKh4EXwHjdUgLrTIW0
"""

import pandas as pd
import numpy as np
import re
import unicodedata
import hashlib
from datetime import datetime
from pathlib import Path


# ============================================================
# CONFIGURATION
# ============================================================

INPUT_FILE = ""

OUTPUT_FILE = ""

OUTPUT_CSV = ""


# ============================================================
# BASIC UTILITIES
# ============================================================

def safe_text(value):
    """
    Convert missing or non-string values safely to text.
    """
    if pd.isna(value):
        return ""
    return str(value)


def normalize_unicode(text):
    """
    Standardize Unicode representation without altering meaning.
    """
    text = safe_text(text)
    return unicodedata.normalize("NFKC", text)


def normalize_whitespace(text):
    """
    Normalize whitespace while preserving paragraph structure.
    """
    text = safe_text(text)

    # Normalize line endings
    text = text.replace("\r\n", "\n").replace("\r", "\n")

    # Replace tabs and non-breaking spaces
    text = text.replace("\t", " ").replace("\u00a0", " ")

    # Collapse repeated horizontal spaces
    text = re.sub(r"[ ]{2,}", " ", text)

    # Remove spaces before punctuation
    text = re.sub(r"\s+([,.;:!?])", r"\1", text)

    # Strip each line
    text = "\n".join(
        line.strip()
        for line in text.splitlines()
    )

    # Collapse excessive blank lines
    text = re.sub(r"\n{3,}", "\n\n", text)

    return text.strip()


# ============================================================
# ITEM CODE NORMALIZATION
# ============================================================

ITEM_CODE_PATTERN = re.compile(
    r"\b([A-Za-z]{2,3})\s*(\d+)\.(\d+)\b"
)


def normalize_item_codes(text):
    """
    Standardize municipal item codes.

    Examples:
    ex 9.9 -> EX9.9
    Ex9.9  -> EX9.9
    """
    text = safe_text(text)

    def replacement(match):
        letters, first, second = match.groups()
        return f"{letters.upper()}{first}.{second}"

    return ITEM_CODE_PATTERN.sub(
        replacement,
        text
    )


# ============================================================
# COMMON WEB BOILERPLATE CLEANING
# ============================================================

def remove_common_boilerplate(text):
    """
    Remove highly generic interface/extraction artifacts.
    """
    text = safe_text(text)

    patterns = [
        r"\bskip to content\b",
        r"\bskip to main content\b",
        r"\bback to top\b",
        r"\bsubscribe!?\b",
        r"\bno results\b",
        r"\bshare this page\b",
        r"\bprint this page\b",
    ]

    for pattern in patterns:
        text = re.sub(
            pattern,
            " ",
            text,
            flags=re.IGNORECASE
        )

    # Standalone extraction labels
    text = re.sub(
        r"(?im)^\s*(image|body)\s*$",
        "",
        text
    )

    # punctuation / separators
    text = re.sub(
        r"(?m)^\s*[|•·!?]\s*$",
        "",
        text
    )

    return normalize_whitespace(text)


# ============================================================
# TORONTO COUNCIL / COMMITTEE AGENDA CLEANING
# ============================================================

def clean_toronto_agenda_page(text):
    """
    Remove City of Toronto council/committee interface chrome while
    preserving decisions, recommendations, tracking status, motions,
    votes, speakers, and other substantive public-record content.
    """
    text = safe_text(text)

    line_patterns = [
        r"^\s*Agenda Item History(?:\s*-\s*.*)?\s*$",
        r"^\s*Share\s*$",
        r"^\s*Share to\s*$",
        r"^\s*Facebook\s*$",
        r"^\s*Twitter\s*$",
        r"^\s*LinkedIn\s*$",
        r"^\s*Print\s*$",
        r"^\s*Close\s*$",
        r"^\s*E-mail\s*$",
        r"^\s*Expand All\s*$",
        r"^\s*Collapse All\s*$",
        r"^\s*See also\s*$",
    ]

    for pattern in line_patterns:
        text = re.sub(
            pattern,
            "",
            text,
            flags=re.IGNORECASE | re.MULTILINE
        )

    # Bare interface "Item" label
    text = re.sub(
        r"(?im)^\s*Item\s*$",
        "",
        text
    )

    # Interface-only item identifier
    text = re.sub(
        r"(?im)^\s*Item\s*-\s*\d{4}\.[A-Z]{2,3}\d+\.\d+\s*$",
        "",
        text
    )

    # Isolated historical item identifier
    text = re.sub(
        r"(?im)^\s*\d{4}\.[A-Z]{2,3}\d+\.\d+\s*$",
        "",
        text
    )

    # Inline sharing artifacts
    text = re.sub(
        r"\bShare\s+to\s+(?:Facebook|Twitter|LinkedIn)\b",
        " ",
        text,
        flags=re.IGNORECASE
    )

    return normalize_whitespace(text)


# ============================================================
# WATERFRONT TORONTO PAGE CLEANING
# ============================================================

def clean_waterfront_toronto_page(text):
    """
    Remove Waterfront Toronto extraction/UI artifacts while preserving
    substantive project content.
    """
    text = safe_text(text)

    text = re.sub(
        r"\|\s*Waterfront Toronto\s+Image\s+",
        " | ",
        text,
        flags=re.IGNORECASE
    )

    text = re.sub(
        r"\bImage\s+(?=[A-Z])",
        "",
        text
    )

    text = re.sub(
        r"\bBody\s+(?=[A-Z])",
        "",
        text
    )

    text = re.sub(
        r"(?im)^\s*Waterfront Toronto\s*$",
        "",
        text
    )

    return normalize_whitespace(text)


# ============================================================
# TTC PAGE CLEANING
# ============================================================

def clean_ttc_page(text):
    """
    Remove TTC page boilerplate that is not useful for retrieval.
    """
    text = safe_text(text)

    text = re.sub(
        r"For more information on this project please send an e-mail to\s+\S+",
        " ",
        text,
        flags=re.IGNORECASE
    )

    text = re.sub(
        r"For the most up-to-date information.*?Waterfront Network Expansion page\.",
        " ",
        text,
        flags=re.IGNORECASE | re.DOTALL
    )

    return normalize_whitespace(text)


# ============================================================
# TORONTO.CA WEBPAGE CLEANING
# ============================================================

def clean_toronto_webpage(text):
    """
    Conservative cleanup for general Toronto.ca webpages.
    """
    text = safe_text(text)

    text = re.sub(
        r"\bImage\s+(?=[A-Z])",
        "",
        text
    )

    text = re.sub(
        r"\bBody\s+(?=[A-Z])",
        "",
        text
    )

    return normalize_whitespace(text)


# ============================================================
# ACCESSIBILITY BOILERPLATE
# ============================================================

def clean_accessibility_boilerplate(text):
    """
    Remove recurring accessibility-format boilerplate when clearly
    separate from substantive document content.
    """
    text = safe_text(text)

    patterns = [
        (
            r"While we aim to provide fully accessible content.*?"
            r"(?:please contact us at\s+\S+\.?|alternate formats.*?(?:\.|\n))"
        ),
    ]

    for pattern in patterns:
        text = re.sub(
            pattern,
            " ",
            text,
            flags=re.IGNORECASE | re.DOTALL
        )

    return normalize_whitespace(text)


# ============================================================
# PDF ARTIFACT CLEANING
# ============================================================

def clean_pdf_artifacts(text):
    """
    Remove obvious PDF layout artifacts while preserving content.
    """
    text = safe_text(text)

    # Standalone page numbers
    text = re.sub(
        r"(?im)^\s*(?:page\s*)?\d+\s*(?:of\s*\d+)?\s*$",
        "",
        text
    )

    # Common City of Toronto extraction artifact
    text = re.sub(
        r"(?im)^\s*[~|]?\s*TORONTO\s*$",
        "",
        text
    )

    # Excessive separators
    text = re.sub(
        r"[-_=]{4,}",
        " ",
        text
    )

    return normalize_whitespace(text)


# ============================================================
# PARAGRAPH RECONSTRUCTION
# ============================================================

def reconstruct_paragraphs(text):
    """
    Rejoin PDF-style hard line wraps while preserving headings,
    numbered lists, bullets, URLs, and genuine paragraph boundaries.

    This improves readability and prepares normalized_text for a later,
    separate chunking stage.
    """
    text = safe_text(text)

    if not text.strip():
        return ""

    lines = text.splitlines()
    rebuilt = []
    buffer = []

    # Typical uppercase report headings
    heading_pattern = re.compile(
        r"^[A-Z][A-Z0-9 /&(),:'’–—\-]{3,}$"
    )

    # Numbered / lettered / bullet list starts
    list_pattern = re.compile(
        r"^\s*(?:\d+[\.\)]|[a-zA-Z][\.\)]|[-•])\s+"
    )

    # URLs and explicit link labels
    url_pattern = re.compile(
        r"^(?:https?://|www\.|Link:)",
        flags=re.IGNORECASE
    )

    # Agenda/report labels that should remain structurally separate
    structural_label_pattern = re.compile(
        r"^(?:"
        r"Decision Type:|"
        r"Status:|"
        r"Wards:|"
        r"Origin|"
        r"Summary|"
        r"Recommendations?|"
        r"Financial Impact|"
        r"Decision History|"
        r"Comments?|"
        r"Background|"
        r"Committee Decision|"
        r"City Council Decision|"
        r"Speakers?|"
        r"Motions?|"
        r"Vote"
        r")$",
        flags=re.IGNORECASE
    )

    def flush_buffer():
        if buffer:
            paragraph = " ".join(
                part.strip()
                for part in buffer
                if part.strip()
            )
            if paragraph:
                rebuilt.append(paragraph)
            buffer.clear()

    for line in lines:
        stripped = line.strip()

        # True paragraph boundary
        if not stripped:
            flush_buffer()
            if rebuilt and rebuilt[-1] != "":
                rebuilt.append("")
            continue

        # Preserve headings
        if heading_pattern.match(stripped):
            flush_buffer()
            rebuilt.append(stripped)
            continue

        # Preserve known structural labels
        if structural_label_pattern.match(stripped):
            flush_buffer()
            rebuilt.append(stripped)
            continue

        # Preserve list starts
        if list_pattern.match(stripped):
            flush_buffer()
            rebuilt.append(stripped)
            continue

        # Preserve URLs / source links
        if url_pattern.match(stripped):
            flush_buffer()
            rebuilt.append(stripped)
            continue

        buffer.append(stripped)

    flush_buffer()

    text = "\n".join(rebuilt)

    # Collapse excessive blank lines
    text = re.sub(
        r"\n{3,}",
        "\n\n",
        text
    )

    return text.strip()


# ============================================================
# AGENDA METADATA / LIST LAYOUT
# ============================================================

def normalize_agenda_metadata_layout(text):
    """
    Improve Toronto agenda formatting by keeping simple metadata labels
    and values together and joining list markers to their first sentence.
    """
    text = safe_text(text)

    labels = [
        "Decision Type",
        "Status",
        "Wards",
    ]

    for label in labels:
        text = re.sub(
            rf"(?im)^({re.escape(label)}):\s*\n\s*([^\n]+)",
            r"\1: \2",
            text
        )

    # Join numbered recommendation marker with first sentence
    text = re.sub(
        r"(?m)^(\d+\.)\s*\n\s*(?=\S)",
        r"\1 ",
        text
    )

    # Join lettered list marker with first sentence
    text = re.sub(
        r"(?m)^([a-zA-Z]\.)\s*\n\s*(?=\S)",
        r"\1 ",
        text
    )

    # Join bullet marker with first sentence
    text = re.sub(
        r"(?m)^([-•])\s*\n\s*(?=\S)",
        r"\1 ",
        text
    )

    return normalize_whitespace(text)


# ============================================================
# MASTER TEXT NORMALIZER
# ============================================================

def normalize_local_politics_text(text, source_url=""):
    """
    Source-aware conservative normalization for the Local Politics Search Agent.

    It removes formatting/interface noise, reconstructs readable paragraphs,
    and preserves substantive municipal-record wording and structure.

    Chunking is intentionally NOT performed here.
    """
    text = safe_text(text)

    if not text.strip():
        return ""

    text = normalize_unicode(text)
    text = normalize_item_codes(text)

    url = safe_text(source_url).lower()

    # Source-specific cleaning
    if "secure.toronto.ca/council" in url:
        text = clean_toronto_agenda_page(text)

    elif "waterfrontoronto.ca" in url:
        text = clean_waterfront_toronto_page(text)

    elif "ttc.ca" in url:
        text = clean_ttc_page(text)

    elif "toronto.ca" in url:
        text = clean_toronto_webpage(text)

    # Safe cross-source cleaning
    text = clean_accessibility_boilerplate(text)
    text = clean_pdf_artifacts(text)
    text = remove_common_boilerplate(text)

    # Reconstruct hard-wrapped prose into readable paragraphs
    text = reconstruct_paragraphs(text)

    # Improve agenda-specific metadata/list layout
    if "secure.toronto.ca/council" in url:
        text = normalize_agenda_metadata_layout(text)

    # Final whitespace cleanup
    text = normalize_whitespace(text)

    return text


# ============================================================
# DATE NORMALIZATION
# ============================================================

def normalize_date(value):
    """
    Convert recognizable dates to YYYY-MM-DD.

    Returns:
        normalized_date, flag
    """
    if pd.isna(value) or value == "":
        return None, "DATE_MISSING"

    if isinstance(value, (pd.Timestamp, datetime)):
        return (
            pd.Timestamp(value).strftime("%Y-%m-%d"),
            None
        )

    raw = str(value).strip()

    # Explicit DD/MM/YYYY
    match = re.fullmatch(
        r"(\d{1,2})/(\d{1,2})/(\d{4})",
        raw
    )

    if match:
        day, month, year = map(
            int,
            match.groups()
        )

        try:
            parsed = datetime(
                year,
                month,
                day
            )
            return (
                parsed.strftime("%Y-%m-%d"),
                None
            )
        except ValueError:
            return raw, "DATE_INVALID"

    parsed = pd.to_datetime(
        raw,
        errors="coerce",
        dayfirst=True
    )

    if not pd.isna(parsed):
        return (
            parsed.strftime("%Y-%m-%d"),
            None
        )

    return raw, "DATE_UNPARSED"


# ============================================================
# TEXT HASH
# ============================================================

def create_text_hash(text):
    """
    Create a SHA-256 hash from normalized text.

    URL is intentionally excluded so identical content at different URLs
    can potentially be detected.
    """
    text = safe_text(text)

    if not text.strip():
        return ""

    canonical = normalize_whitespace(
        normalize_unicode(text)
    )

    return hashlib.sha256(
        canonical.encode("utf-8")
    ).hexdigest()


# ============================================================
# QUALITY FLAGS
# ============================================================

def generate_quality_flags(row):
    """
    Generate normalization / extraction review flags.
    """
    flags = []

    text = safe_text(
        row.get("normalized_text", "")
    )

    raw_text = safe_text(
        row.get("raw_text", "")
    )

    exceptions = safe_text(
        row.get("V15_Exceptions", "")
    )

    tier = safe_text(
        row.get("V16_Tier", "")
    )

    # Text availability
    if not text.strip():

        if (
            "OUTBOUND_LINK_ONLY" in exceptions
            or "outbound-link-only" in tier
        ):
            flags.append("OUTBOUND_LINK_ONLY")

        elif (
            "FETCH_FAILED" in exceptions
            or "P0-failed" in tier
        ):
            flags.append("FETCH_FAILED")

        elif (
            "ROBOTS_DISALLOWED" in exceptions
            or "robots-blocked" in tier
        ):
            flags.append("ROBOTS_BLOCKED")

        else:
            flags.append("TEXT_EMPTY")

    else:

        if len(text) < 100:
            flags.append("TEXT_VERY_SHORT")

        elif len(text) < 300:
            flags.append("TEXT_SHORT")

    # Possible truncation
    if 480 <= len(raw_text) <= 520:
        flags.append("POSSIBLE_CONNECTOR_TRUNCATION")

    # Redaction review
    if "[PRIVATE_NAME_REDACTED]" in text:
        flags.append("PII_REDACTION_REVIEW")

    if "[EMAIL_REDACTED]" in text:
        flags.append("EMAIL_REDACTED")

    if "[PHONE_REDACTED]" in text:
        flags.append("PHONE_REDACTED")

    if "[ADDRESS_REDACTED]" in text:
        flags.append("ADDRESS_REDACTED")

    # OCR / extraction
    if "OCR_APPLIED" in exceptions:
        flags.append("OCR_USED")

    if "LOW_CONFIDENCE_EXTRACTION" in exceptions:
        flags.append("LOW_EXTRACTION_CONFIDENCE")

    # Date
    date_flag = safe_text(
        row.get(
            "date_normalization_flag",
            ""
        )
    )

    if date_flag:
        flags.append(date_flag)

    return flags


# ============================================================
# LOAD DATA
# ============================================================

print("Loading connector output...")

df = pd.read_excel(
    INPUT_FILE
)

print(
    f"Loaded {len(df)} records "
    f"with {len(df.columns)} columns."
)

print("\nColumns:")
print(df.columns.tolist())


# ============================================================
# VERIFY REQUIRED COLUMNS
# ============================================================

if "raw_text" not in df.columns:
    raise ValueError(
        "\nThe connector output does not contain a 'raw_text' column.\n"
        "Run the retrieval-enabled pathway connector first, then rerun "
        "this normalization script."
    )

if "V13_SourceLink" not in df.columns:
    raise ValueError(
        "\nThe connector output does not contain 'V13_SourceLink'.\n"
        "Source-aware normalization requires the source URL."
    )


# ============================================================
# PRESERVE RAW TEXT
# ============================================================

df["raw_text"] = df[
    "raw_text"
].apply(safe_text)


# ============================================================
# NORMALIZE TEXT
# ============================================================

print("\nNormalizing full source text...")

df["normalized_text"] = df.apply(
    lambda row: normalize_local_politics_text(
        row.get("raw_text", ""),
        row.get("V13_SourceLink", "")
    ),
    axis=1
)


# ============================================================
# NORMALIZE DATES
# ============================================================

print("Normalizing dates...")

normalized_dates = df[
    "V01_Date"
].apply(
    normalize_date
)

df["normalized_date"] = (
    normalized_dates
    .apply(lambda x: x[0])
)

df["date_normalization_flag"] = (
    normalized_dates
    .apply(
        lambda x: x[1] or ""
    )
)


# ============================================================
# CREATE TEXT HASH
# ============================================================

print("Creating normalized text hashes...")

df["normalized_text_hash"] = df[
    "normalized_text"
].apply(
    create_text_hash
)


# ============================================================
# ADD NORMALIZATION METADATA
# ============================================================

df["normalization_version"] = (
    NORMALIZATION_VERSION
)

df["normalized_at"] = (
    pd.Timestamp.utcnow()
    .isoformat()
)


# ============================================================
# GENERATE QUALITY FLAGS
# ============================================================

print("Generating quality flags...")

df["normalization_flags"] = df.apply(
    generate_quality_flags,
    axis=1
)

df["normalization_flags"] = (
    df["normalization_flags"]
    .apply(
        lambda flags:
        " | ".join(flags)
    )
)


# ============================================================
# BASIC QUALITY REPORT
# ============================================================

print("\n" + "=" * 60)
print("NORMALIZATION REPORT")
print("=" * 60)

print(
    "\nTotal records:",
    len(df)
)

print(
    "Records with raw text:",
    (
        df["raw_text"]
        .str.strip()
        .ne("")
        .sum()
    )
)

print(
    "Records with normalized text:",
    (
        df["normalized_text"]
        .str.strip()
        .ne("")
        .sum()
    )
)

print(
    "Records with flags:",
    (
        df["normalization_flags"]
        .str.strip()
        .ne("")
        .sum()
    )
)


# ============================================================
# TEXT LENGTH STATISTICS
# ============================================================

df["raw_text_length"] = df[
    "raw_text"
].str.len()

df["normalized_text_length"] = df[
    "normalized_text"
].str.len()

print(
    "\nRaw text length statistics:"
)

print(
    df["raw_text_length"]
    .describe()
)

print(
    "\nNormalized text length statistics:"
)

print(
    df["normalized_text_length"]
    .describe()
)


# ============================================================
# CHECK WHETHER NORMALIZATION CHANGED TEXT
# ============================================================

df["text_changed_by_normalization"] = (
    df["raw_text"]
    !=
    df["normalized_text"]
)

print(
    "\nRecords changed by normalization:",
    df[
        "text_changed_by_normalization"
    ].sum()
)


# ============================================================
# DUPLICATE CHECK
# ============================================================

duplicates = df[
    (
        df[
            "normalized_text_hash"
        ].duplicated(
            keep=False
        )
    )
    &
    (
        df[
            "normalized_text_hash"
        ] != ""
    )
].copy()

print(
    "\nPotential duplicate records:",
    len(duplicates)
)

if len(duplicates) > 0:

    print(
        "\nPotential duplicate documents:"
    )

    display(
        duplicates[
            [
                "V04_Title",
                "V13_SourceLink",
                "normalized_text_hash"
            ]
        ].sort_values(
            "normalized_text_hash"
        )
    )


# ============================================================
# FLAG SUMMARY
# ============================================================

flag_counts = (
    df["normalization_flags"]
    .str.split(
        r"\s*\|\s*"
    )
    .explode()
)

flag_counts = flag_counts[
    flag_counts.notna()
    &
    (flag_counts != "")
]

if len(flag_counts) > 0:

    print(
        "\nNormalization flag counts:"
    )

    print(
        flag_counts.value_counts()
    )


# ============================================================
# REVIEW TABLE
# ============================================================

review_df = df[
    df[
        "normalization_flags"
    ].str.strip().ne("")
].copy()

if len(review_df) > 0:

    print(
        f"\n{len(review_df)} records "
        "have one or more review flags."
    )

    display(
        review_df[
            [
                "V04_Title",
                "V13_SourceLink",
                "normalization_flags",
                "raw_text_length",
                "normalized_text_length"
            ]
        ]
    )


# ============================================================
# BEFORE / AFTER SAMPLE
# ============================================================

print(
    "\nSample before / after normalization:"
)

display(
    df[
        [
            "V04_Title",
            "V13_SourceLink",
            "raw_text",
            "normalized_text",
            "normalization_flags"
        ]
    ].head(10)
)


# ============================================================
# EXPORT
# ============================================================

print("\nSaving normalized corpus...")

df.to_excel(
    OUTPUT_FILE,
    index=False
)

df.to_csv(
    OUTPUT_CSV,
    index=False
)

print(
    "\nSaved Excel file:"
)
print(
    OUTPUT_FILE
)

print(
    "\nSaved CSV file:"
)
print(
    OUTPUT_CSV
)

print(
    "\nNormalization complete."
)